apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: labs-postgres-data
  namespace: labs
spec:
  storageClassName: manual
  volumeName: labs-postgres-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
