apiVersion: v1
kind: Secret
metadata:
  name: labs-app-secrets
  namespace: labs
type: Opaque
stringData:
  POSTGRES_DB: labs
  POSTGRES_USER: labs
  POSTGRES_PASSWORD: labs
  DATABASE_URL: postgres://labs:labs@labs-postgres:5432/labs?sslmode=disable
