name: CI

on:
  push:
  pull_request:

jobs:
  pipeline:
    uses: ./.github/workflows/image-pipeline.yml
    permissions:
      contents: read
      packages: write
      security-events: write
    secrets: inherit
    with:
      git_ref: ${{ github.sha }}
      image_version: ci-0.0.${{ github.run_number }}
      publish_images: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
